#!/bin/bash

blue=$(tput setaf 51)
reset=$(tput sgr0)
purple=$(tput setaf 201) #92

echo -e "
      ___                   ${blue}name${reset}        ${purple}${reset}  zac the wise
     /\__\                  ${blue}age${reset}         ${purple}${reset}  young
    /::|  |                 ${blue}langs${reset}       ${purple}${reset}  py, sh
   /:/:|  |                 ${blue}edu${reset}         ${purple}${reset}  tafe nsw
  /:/|:|  |__               ${blue}kn${reset}          ${purple}歷${reset} networking,
 /:/ |:| /\__\\                          ${purple}${reset}  cloud,
 \/__|:|/:/  /                          ${purple}${reset}  linux,
     |:/:/  /                           ${purple}${reset}  hardware
     |::/  /                ${blue}os${reset}          ${purple}${reset}  PogOS
     |:/  /                 ${blue}todo${reset}        ${purple}${reset}  java, tts, image recog
     |/__/    
"