#!/bin/bash

# Add options command
# startup -addname "Pycord Developer" "Automation" "Random Projects" "Desktop"
# writes each to a file then...
#startup -addlocation "~/Desktop/desktop_folders/pycordDeveloper" etc etc

PS3='Please enter your choice: '
options=("Pycord Developer" "Automation" "Random Projects" "Desktop")
select opt in "${options[@]}"
do
    case $opt in
        "Pycord Developer")
            cd ~/Desktop/desktop_folders/pycordDeveloper
            pwd
            break
            ;;
        "Automation")
            cd ~/Desktop/Projects/Automation
            pwd
            break
            ;;
        "Random Projects")
            echo "you chose choice $REPLY which is $opt"
            cd ~/Desktop/Projects/randomProjects
            pwd
            break
            ;;
        "Desktop")
            echo "you chose choice $REPLY which is $opt"
            cd ~/Desktop/
            pwd
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
