#!/bin/bash

# Add options command
# startup -addname "Pycord Developer" "Automation" "Random Projects" "Desktop"
# writes each to a file then...
# startup -addlocation "~/Desktop/desktop_folders/pycordDeveloper" etc etc
PS3='Please enter your choice: '
options=("Pycord Developer" "Automation" "Random Projects" "Desktop" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Pycord Developer")
            cd ~/Desktop/desktop_folders/pycordDeveloper
            pwd
            break
            ;;
        "Automation")
            cd ~/Desktop/Projects/Automation
            pwd
            break
            ;;
        "Random Projects")
            cd ~/Desktop/Projects/randomProjects
            pwd
            break
            ;;
        "Desktop")
            cd ~/Desktop/
            pwd
            break
            ;;
        "Quit")
            echo "Quitting..."
            break
            ;;
        *)
            echo "invalid option $REPLY"
            ;;
    esac
done
