#!/usr/bin/bash

echo -e "
${GREEN#  }                 ###               ${fieldlist[0]}
${GREEN#  }               ####                ${fieldlist[1]}
${GREEN#  }               ###                 ${fieldlist[2]}
${GREEN#  }       #######    #######          ${fieldlist[3]}
${YELLOW# }     ######################        ${fieldlist[4]}
${YELLOW# }    #####################          ${fieldlist[5]}
${RED#    }    ####################           ${fieldlist[6]}
${RED#    }    ####################           ${fieldlist[7]}
${RED#    }    #####################          ${fieldlist[8]}
${PURPLE# }     ######################        ${fieldlist[9]}
${PURPLE# }      ####################         ${fieldlist[10]}
${BLUE#   }        ################           ${fieldlist[11]}
${BLUE#   }         ####     #####            ${fieldlist[12]}
${normal}
"



clear
while sleep 1; do
    user=$(whoami)
    date=$(date +%F)
    day=$(date +"%a")
    time=$(date +"%T")
    ip=$(ipconfig getifaddr en4)
    curl -sH 'Accept: application/vnd.github.cloak-preview' \https://api.github.com/search/commits?q=author:TechWiz-3+author-date:$date > curl_output.json
    numberofcommits=$(jq '.total_count' curl_output.json)
    #howmany=$(grep -o '"items": *"[^"]*"' curl_output.json | grep -o '"[^"]*"$')
    kernel=$(uname -rs)
    if [ $numberofcommits -eq 0 ] ; then
        gitcommits=false
    else
        gitcommits=true
    fi

    if [ $gitcommits == true ]; then
        commits="$numberofcommits commits today"
    else
        commits="No commits yet"
    fi
    cpu=$(ps -A -o %cpu | awk '{s+=$1} END {print s "%"}')
    ram=$(top -l 1 -s 0 | grep PhysMem)
    remove="PhysMem: "
    ram=${ram//$remove}


    tput cup 0 0
    echo -e "
    User: $user
    Hostname: $HOSTNAME
    Date: $date
    Day: $day""day
    Time: $time
    IP: $ip
    Commits: $commits
    Kernel: $kernel
    CPU: $cpu
    RAM: $ram"
done

echo -e "\033[1mComputer Stats:\033[0m"
cpuinfo=$(sysctl -n machdep.cpu.brand_string)
echo $cpuinfo

# while sleep 1; do
#     cpu=$(ps -A -o %cpu | awk '{s+=$1} END {print s "%"}')
#     echo "$cpu"
#     i=$((i+1))
#     echo $i
# done