name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Heyoo thanks a lot for submitting your first issue, Zac will respond to it as soon as possible'
        pr-message: 'Heyoo thanks a lot for submitting your PR, Zac will check it as soon as possible'
